In [4]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

In [6]:
df=pd.read_csv('Salary_dataset.csv')

In [11]:
x=df['YearsExperience']
y=df['Salary']

In [29]:
x=np.array(x).reshape(-1,1)
y=np.array(y).reshape(-1,1)

In [32]:
# model
model=LinearRegression().fit(x,y)

In [35]:
# R**2 , coef of determination
r_sq=model.score(x,y)
r_sq 

0.9569566641435086

In [39]:
# b0
model.intercept_

array([24848.20396652])

In [40]:
# b1
model.coef_

array([[9449.96232146]])

In [41]:
y_pred=model.predict(x)
y_pred

array([[ 36188.15875227],
       [ 38078.15121656],
       [ 39968.14368085],
       [ 44693.12484158],
       [ 46583.11730587],
       [ 53198.09093089],
       [ 54143.08716303],
       [ 56033.07962732],
       [ 56033.07962732],
       [ 60758.06078805],
       [ 62648.05325234],
       [ 63593.04948449],
       [ 63593.04948449],
       [ 64538.04571663],
       [ 68318.03064522],
       [ 72098.0155738 ],
       [ 73988.00803809],
       [ 75878.00050238],
       [ 81547.97789525],
       [ 82492.9741274 ],
       [ 90052.94398456],
       [ 92887.932681  ],
       [100447.90253816],
       [103282.8912346 ],
       [108007.87239533],
       [110842.86109176],
       [115567.84225249],
       [116512.83848464],
       [123127.81210966],
       [125017.80457395]])